name: 02 - 1 - Staging - Docker GHCR

on:
  workflow_call:
    inputs: 
      docker-mode:
        required: false
        type: string
        default: ""

env: 
  REGISTERY: ghcr.io
  USERNAME: ${{ github.actor}}
  IMAGE_NAME: ${{ github.repository }}  #orga/repo

jobs:
  Display_Data:
    runs-on: ubuntu-latest
    steps:
      - name: Log info
        run: |
          echo "Docker Registery: ${{ env.REGISTERY }}"
          echo "Docker Username: ${{ env.USERNAME }}"
          echo "Docker Registery: ${{ env.IMAGE_NAME }}"
          echo "Docker Registery: ${{ inputs.docker-mode }}"
  
  Build_Push_Docker:
    runs-on: ubuntu-latest

    steps: 
      - name: Log in to Github Container Registery
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTERY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Down case Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}
      
      - name: Back Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: backend
          push: true
          tags:  ${{ env.REGISTERY }}/${{ env.IMAGE_NAME_LOWER }}-back:latest

      - name: Front Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: frontend
          push: true
          tags:  ${{ env.REGISTERY }}/${{ env.IMAGE_NAME_LOWER }}-front:latest
          build-args: MODE=${{inputs.docker-mode}}
  